# Builds the Jekyll site and deploys it to Firebase hosting
name: Deploy each push
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Fix permissions
        uses: docker://jekyll/builder:4.1.0
        with:
          entrypoint: "/bin/chown"
          args: -R jekyll:jekyll .

      - name: Build site
        uses: docker://jekyll/builder:4.1.0
        with:
          args: jekyll build

      - name: Archive built site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
